package-lock.json

Happened automatically after an `npm install`.

fix(deps): Fix name in package-lock.json

---

package.json
resources/roca.brs
src/index.js

Our testing API will be shipped with this node module via the `files` array in package.json, making it accessible to anyone who runs `roca`.  By producing TAP-compliant output, we can let consumers choose their preferred reporter.  I've tested this output with:
* https://github.com/substack/tap-colorize
* https://github.com/calvinmetcalf/tap-nyan
* https://github.com/scottcorgan/tap-spec
* https://github.com/substack/faucet
Example test file:
```brightscript
function addOne(i)
return i + 1
end function
sub main()
describe("addOne", sub()
describe("nested", sub()
describe("L3", sub()
it("works", sub()
m.pass()
end sub)
end sub)
it("adds one to positive integers", sub()
if addOne(1) = 2 then
m.pass()
else
m.fail()
end if
end sub)
it("adds one to negative integers", sub()
if addOne(-1) = 0 …
```

feat(brs): Add initial version of roca.brs

---

package-lock.json
package.json

My bad!  `@hulu/roca` isn't currently `npm install`-able without the `cli.js` file.

fix(build): Ensure cli/bin.js gets packed for publication

---

bin/cli.js
package-lock.json
package.json
src/index.js

Rather than hand-writing our own reporters, we can pipe `brs`'s `stdout` directly through `tap-mocha-reporter` and leverage all of the reporters that it supports.  That's more than enough to get us started, and allows `roca` users to write their own TAP reporters as desired!

feat(report): Include tap mocha reporter by default

---

resources/roca_lib.brs

The case index in a suite should be reset after executing the whole suite.

fix: Tap reporter uses correct index case

---

resources/tap.brs

`getInent` isn't a real function!  I meant `getIndent`!

fix(tap): Fix typo in TAP diagnostics

---

resources/assert_lib.brs
resources/roca_lib.brs
resources/tap.brs
src/index.js

I've started a very basic assertion library with just a few methods. The idea is to make developers' lives simpler when writing brightscript tests. 🎅 
Currently just one assertion per case is supported and there is no support for messages on failed assertions, will work on that later. 
Examples of usage:
```
describe("testing assertion", sub()
m.it("tests equality", sub()
m.assert.equal(1, 2)
end sub)
m.it("test isTrue", sub()
m.assert.isTrue(true)
end sub)
m.it("tests invalid", sub()
m.assert.isInvalid(invalid)
end sub)
end sub)
```

feat(api): Basic assertion library

---

docs/README.md
resources/roca_lib.brs

BREAKING-CHANGE Forcing all calls to `describe` through an associative array makes its implementation a bit simpler, and makes usage more consistent for devs writing tests!  The new interface is:
```brightscript
function main(args as object) as object
return roca(args).describe("foo", sub()
m.it("a test case", sub()
' test logic goes here
end sub)
m.describe("sub-suite", sub()
m.it("case 1", sub()
end sub)
m.it("case 2", sub()
end sub)
end sub)
end sub)
end function
```

fix(scope): Allow nested test suites after `m` scope adjustments

---

package-lock.json
package.json

0.17.1 prevents an infinite loop when processing custom components that extend not-yet-implemented components.
More details at https://github.com/sjbarag/brs/releases/tag/v0.17.1

chore(deps): Update brs from 0.17.0 to 0.17.1

---

docs/README.md
resources/roca_lib.brs
resources/roca_main.brs

This implements `fdescribe` and `xdescribe` (#21).
Also, this modifies the existing focus logic so that we **ignore non-focused tests instead of skipping them**. This is the [same behavior as `mocha`](https://github.com/mochajs/mocha/blob/master/lib/suite.js#L459-L482), and makes test runs that use `fdescribe`/`fit` have much cleaner output.
fixes #21

Implement fdescribe and xdescribe

---

docs/README.md
resources/roca_lib.brs

In the current state of the assert lib, multiple asserts will overwrite each other.
```
function main(args as object) as object
return roca(args).describe("test suite", sub()
m.it("test case", sub()
m.assert.isTrue(false)        ' should cause the test case to fail
m.assert.isTrue(true)         ' overwrites the previous assert, making the test case pass
end sub)
end sub)
end function
```
With this change, the first failure that the test case encounters will be preserved, and that message will show to the user.
Also, this updates the Readme with info about `assert`s.

fix(assert): don't allow assert failures to be overwritten

---

bin/cli.js
docs/README.md
src/index.js

This adds support for the user to supply a path to a global setup file. This is helpful for the user because often there are test utilities that are needed in multiple unit test files. But without a global setup file, the only way to create those utilities would be to have them in `source/`, which would mean they get bundled with the actual application.
This is pretty similar to, for example, Jest's [config option](https://jestjs.io/docs/en/configuration#globalsetup-string).

feat: add support for a global setup file

---

package-lock.json
package.json
resources/roca_main.brs

This allows writing a test file like:
```brightscript
' group.test.brs
function main(args as object)
r = roca(args)
return [
Command_spec(r),
Util_spec(r)
]
end function
```
with test cases being collocated in the sources like:
```brightscript
' source/utils/Util.spec.brs
function Util_spec(roca)
return roca.describe("Util suite", sub()
m.it("should pass", sub()
m.pass()
end sub)
end sub)
end function
```

Allow a test file to return multiple suite objects

---

resources/roca_main.brs
resources/tap.brs

When `brs.runInScope` fails due to an exception, it returns `invalid`. When that happens, we should bail on running the rest of the tests so that we don't print a bunch of `test count !== plan` errors. `Bail out!` is in the TAP specification for when you want your test to bail.

fix(lib): bail after brs throws exception

---

README.md

This uses [`doctoc`](https://github.com/thlorenz/doctoc) (no particular attachment to that tool, just found it via a quick google) to generate a Table of Contents. This will make the `README` friendlier and more navigable.

feat(doc): add table of contents to README

---

package.json
resources/roca_main.brs

This calls [`_brs_.resetMocks`](https://github.com/sjbarag/brs#_brs_resetmocks) between test files to prevent test files from interfering with each other.
Unfortunately, there's no unit tests set up (yet!) for this project, but rest assured that I have tested this in a brightscript repo to confirm that it works as expected.

feat(brs): reset mocks between test files

---

README.md
resources/roca_lib.brs

```brightscript
function main(args as object) as object
return roca(args).describe("test suite", sub()
m.addContext({
someValue: "value"
beforeEach: function()
return { data: "data" }
end function
})
m.it("has a test case", sub()
o = m.beforeEach()
m.assert.equal("data", o.data, "I can call a function")
m.assert.equal("value", m.someValue, "I can get a value")
m.pass()
end sub)
end sub)
end function
```
Maybe adresses issue #20

feat(api): Allow passing fields to cases

---

package-lock.json

Looks like we got out of sync with the `brs` version in the `package.json`/`package-lock.json`. This PR resolves that.

fix(dependencies): correct brs version mismatch

---

resources/roca_main.brs

Currently, if there is an error in the `m.describe` block, we do nothing on the first (non-exec) pass when the error is encountered, and then silently skip the entire file on the second (exec) pass. This is pretty confusing for the user, _especially_ if they are using `m.fdescribe` or `m.fit`, and suddenly we're running every test except for the (broken) focused ones.
This doesn't happen for code inside of `m.it` blocks or actual code that's being tested, because we don't execute that code until our second pass.
Let's fail early when we encounter a runtime exception.

fix(lib): don't skip tests if brs throws an exception

---

resources/roca_main.brs

Currently, if you do `roca(args).fdescribe( ... )` it doesn't focus correctly on that suite. This PR fixes that.

fix(api): make fdescribe work on roca object

---

resources/roca_lib.brs

`m.addContext(ctx)` appends everything in `ctx` to `m` object so that it's accessible within test cases. However, it currently isn't accessible in suites or the `roca` object. This PR makes it accessible from suites/`roca`.

feat(api): make context accessible from suite objects

---

README.md
bin/cli.js
package-lock.json
package.json
resources/roca_main.brs
src/index.js

This allows a consumer to pass `--forbid-focused` to the `roca` cli, which will then cause the test runner to exit with error if it detects a focused test case, i.e. it emulates the [Mocha cli `--forbid-only`](https://mochajs.org/#command-line-usage). This is useful to be able to configure CI/CD to avoid accidentally checking in focused tests/suites.

feat(cli): add --forbid-focused flag

---

README.md
package-lock.json
package.json
resources/roca_main.brs

Previously we only searched in `tests/*.test.brs` files because `MatchFiles` doesn't work recursively.  A combination of `ListDir` and `MatchFiles` lets us manually do that search recursively -- luckily it's not terribly slow as far as I can tell!
fixes #18
closes #10 (no need for configuration if we search everything)

feat(discovery): Find tests recursively from package root

---

.github/workflows/pull-request.yaml
jest.config.js
package-lock.json
package.json
src/index.js
test/README.md
test/selection/fdescribe/tests/fdescribe.test.brs
test/selection/fit/tests/excluded.test.brs
test/selection/fit/tests/fit.test.brs
test/selection/mixed/tests/mixed.test.brs
test/selection/selection.test.js
test/selection/xdescribe/tests/xdescribe.test.brs
test/selection/xit/tests/unmodified.test.brs
test/selection/xit/tests/xit.test.brs
test/simple-suites/multiple-files/tests/bar.test.brs
test/simple-suites/multiple-files/tests/foo.test.brs
test/simple-suites/nested/tests/nested.test.brs
test/simple-suites/no-cases/tests/no-cases.test.brs
test/simple-suites/simple-suites.test.js
test/simple-suites/single-level/tests/single-level.test.brs
test/util.js

We previously didn't have any tests for this project, so we can't check for regressions before publishing a new version!  
This expands the POC from #45 into some full-fledged tests, complete with a small explanation of the testing approach (in `test/README.md`) and support for continuous testing via GitHub Actions.

test: Add tests for roca

---

bin/cli.js
resources/roca_main.brs

While doing unit testing, I noticed that if a runtime exception occurred in my code, then roca would pile on with its own "mismatched return type" error.

fix(error-handling): roca main always returns an assoc array

---

README.md
resources/roca_lib.brs
test/parameterized/fit_each/tests/01-fit_each.test.brs
test/parameterized/it_each/tests/01-it_each.test.brs
test/parameterized/parameterized.test.js
test/parameterized/xit_each/tests/01-xit_each.test.brs

- Added `m.it_each` feature
- Updated `m.it`, now we can pass args to passed function.
- Updated README.md
closes #47

feat(api): Add `m.it_each` to support for parameterized tests

---

README.md

This puts the assert lib API into the API section, and puts each function in the table of contents for better discoverability.

chore(docs): put assert functions in API section

---

README.md
bin/cli.js
package-lock.json
package.json
src/coverage.js
src/index.js

This allows for code coverage reporting. It gets coverage data using the `brs` API from https://github.com/sjbarag/brs/pull/525, and generates the reports using [IstanbulJS](https://istanbul.js.org/).

feat(coverage): add code coverage reporting

---

package.json

This adds the `src` dir to the list of files. `src/coverage.js` wasn't getting bundled along with the rest of the files, which causes `roca` to break.

fix(config): add src dir to files in package.json

---

package-lock.json
package.json
src/index.js

This uses the new [configurable component directory feature from `brs`](https://github.com/sjbarag/brs/pull/549) to search `test` and `tests` for XML files. This will enable easier testing of "utility" files that aren't tied 1:1 with a source component.

feat(brs): search test and tests for component definitions

---

.github/workflows/pull-request.yaml

Remove hurtful language by following the example of git [1] and GitHub [2], i.e. rename `master` to `main`.
[1] https://lore.kernel.org/git/pull.783.git.1604829561838.gitgitgadget@gmail.com/
[2] https://github.com/github/renaming

fix(infra): Rename default branch from `master` to `main`

---

resources/assert_lib.brs

This PR fixes issue #63 __roca_deepEquals compare objects with different types as equal

Fix wrong comparison for __roca_deepEquals

---

package.json

This adds `prepublishOnly` so that our package gets built before it gets published.

fix(infra): add a prepublishOnly script

---

resources/assert_lib.brs

It's causing numeric comparison unreliable in deepEquals.

fix(assert) check if both are numeric instead of comparing

---

resources/assert_lib.brs

This converts all expected/actual values to strings so that we always get a diff in the output for failed tests. This is especially nice for `deepEquals`, where this:
```brs
m.assert.deepEquals( { foo: ["bar"] }, { foo: ["baz"] }, "expected deep equal")
```
results in:

fix(assert): convert values to string for better output diffs

---

resources/assert_lib.brs
resources/tap.brs
resources/tap/main.brs
resources/tap/tap.brs
src/index.ts
src/runner/TestRunner.ts

Closes #72. This converts all of our expected/actual values to be YAML multiline strings, which has the effect of escaping any YAML special characters that may appear in strings/variable names.
Also, converting everything to a string ensures that `tap-mocha-reporter` always shows an error diff -- it does not print _any_ diff output if the types of expected vs. actual are not the same.
This also fixes a bug where `roca.log("message")` was not working due to a reference error.

fix(reporter): Use multiline strings to escape YAML

---

docs/api/reference/_sidebar.md
docs/api/reference/implementation-gaps.md

This moves the [implementation gaps doc](https://github.com/sjbarag/brs/blob/main/docs/NotImplemented.md) from `brs` to the doc site.

feat(docs): add implementation gaps

---

docs/_sidebar.md
docs/guides/README.md
docs/guides/testing-functions.md
docs/guides/testing-private-functions.md
docs/resources/faq.md

Closes #78 
To view the docs locally, run `npm run serve-docs`.

feat(docs): add function testing guide

---

docs/api/reference/mocks.md
docs/guides/testing-functions.md

chore(docs): update mockFunction API documentation

---

src/reporter/JestReporter.ts

Whoops, our Jest reporter was double-counting all non-failure tests.

fix(reporter): don't double-count tests

---

docs/api/reference/asserts.md
resources/assert_lib.brs

Resolves #34
Added new `isValid` assertion. Updated docs.
The only thing to note here is that there is no `expected` value because we're expecting anything except `invalid`. So I'm passing `non-invalid` string there.
Sample test case:
```
m.it("in the test case", sub()
m.assert.isInvalid({}, "should be invalid")
m.assert.isValid(invalid, "should be valid")
end sub)
```
When `isInvalid` not commented out:
When `isValid` not commented out:

Issue #34 Add isValid assertion

---

bin/cli.js
docs/api/cli-options.md
docs/getting-started/quick-start.md
package-lock.json
package.json
src/index.ts
src/util.ts
test/e2e/util.js
test/runner/file-match.test.ts

This adds support for running specific test files from the command line. Similar to `jest` (see [docs](https://jestjs.io/docs/cli#running-from-the-command-line)) it allows the user to specify any strings that appear in the file path, and we'll find files that match or partially match those strings.
Maybe this handles #32? At least, it partially does -- it doesn't filter by suite or test names, but rather by file names.
For example, consider this file structure:
```
root/
|__ foo/
|__ bar.test.brs
|__ baz.test.brs
|__ fly-you-fools.test.brs
```
With the command: `roca foo`, we'd end up testing:
```
root/foo/bar.test.brs
root/foo/baz.test.brs
root/fly-you-fools.test.brs
```
With the command `roca bar` or `roca bar.test.brs` we'd end up testing:
```
root/foo/bar.test.brs
```
For more …

feat(cli): support testing specific files

---

src/index.ts
src/reporter/JestReporter.ts
src/runner/JestRunner.ts

- Added correct exit code when test fails
- Added correct exit code when file fails execution
- Added correct exit code when `forbid-focused` option is passed and there is at least one focused test
fixes #94

fix(runner): return correct exit code when something fails

---

resources/assert_lib.brs
resources/roca_lib.brs
src/reporter/utils.ts
test/reporter/jest-reporter.test.ts

`brs` [recently introduced](https://github.com/sjbarag/brs/commit/08baf5e3a78c058c756bc12c1b50d60ad9886dce) better handling of associative array keys, and case-sensitive keys are now the default when printing assoc arrays. However, this broke our `stackFrames` implementation because we used camel case. This results in a runtime error that prints out a **Javascript** stack trace to the user whenever they have a failed test case.
An easy, backwards-compatible fix is to use snake case instead!

fix(reporter): don't use case sensitive keys

---

package.json
resources/tap/tap.brs
src/coverage.ts
src/index.ts
src/reporter/JestReporter.ts
src/runner/JestRunner.ts
src/runner/TestRunner.ts
test/reporter/jest-reporter.test.ts
test/runner/file-match.test.ts
yarn.lock

Jira: [HULUROKU-7877](https://jira.disneystreaming.com/browse/HULUROKU-7877)
- Replace the "brs" package with "@rokucommunity/brs" in package.json
- Use @rokucommunity/brs version 0.45.2 (later versions introduce issues with roca's unit tests)
- Update roca typescript files to use the new namespace "@rokucommunity/brs"

[HULUROKU-7877] Replace brs package with @rokucommunity/brs version 0.45.2

---

package.json
src/index.ts
tsconfig.json
yarn.lock

Jira: [HULUROKU-7919](https://jira.disney.com/browse/HULUROKU-7919)
- Update to `@rokucommunity/brs` version 0.47.4
- Invoke the brs interpreter with a `noColor` flag to preserve the TAP interface (see [Test Anything Protocol](https://testanything.org/) )

[HULUROKU-7919] Suppress color output from the BRS interpreter
